name: Release Extension

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq zip glib-2.0-dev

      - name: Get version from release tag
        id: get_version
        run: |
          TAG_NAME=$(echo ${{ github.event.release.tag_name }})
          VERSION=${TAG_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update version in metadata.json
        run: |
          jq ".version = ${{ env.VERSION }}" metadata.json > metadata.json.tmp
          mv metadata.json.tmp metadata.json

      - name: Compile schemas
        run: make compile-schemas

      - name: Create package
        run: make package

      - name: Get extension UUID
        id: get_uuid
        run: echo "UUID=$(jq -r '.uuid' metadata.json)" >> $GITHUB_ENV

      - name: Upload Release Asset
        id: upload_release_asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.UUID }}.zip
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.draft }}
          prerelease: ${{ github.event.release.prerelease }}
